# Generated by Django 4.2.3 on 2023-07-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('url_product', models.URLField(verbose_name='url')),
                ('url_photo', models.URLField(verbose_name='photo')),
                ('price', models.PositiveIntegerField(max_length=50, verbose_name='title')),
            ],
        ),
    ]
